SiteAgencia/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SiteAgencia.Models;

namespace SiteAgencia.Controllers
{
    public class ClientesController : Controller
    {
        private readonly Conectar _context;

        public ClientesController(Conectar context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cliente.ToListAsync());
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Email,Cpf,Senha")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Email,Cpf,Senha")] Cliente cliente)
        {
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Cliente.FindAsync(id);
            _context.Cliente.Remove(cliente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Cliente.Any(e => e.Id == id);
        }
    }
}

SiteAgencia/Controllers/VendasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SiteAgencia.Models;

namespace SiteAgencia.Controllers
{
    public class VendasController : Controller
    {
        private readonly Conectar _context;

        public VendasController(Conectar context)
        {
            _context = context;
        }

        // GET: Vendas
        public async Task<IActionResult> Index()
        {
            var conectar = _context.Compra.Include(c => c.cliente).Include(c => c.destino);
            return View(await conectar.ToListAsync());
        }

        // GET: Vendas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compras = await _context.Compra
                .Include(c => c.cliente)
                .Include(c => c.destino)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (compras == null)
            {
                return NotFound();
            }

            return View(compras);
        }

        // GET: Vendas/Create
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.Cliente, "Id", "Nome");
            ViewData["DestinoId"] = new SelectList(_context.Destino, "Id", "Destino");
            return View();
        }

        // POST: Vendas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClienteId,DestinoId")] Compras compras)
        {
            if (ModelState.IsValid)
            {
                _context.Add(compras);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Cliente, "Id", "Nome", compras.ClienteId);
            ViewData["DestinoId"] = new SelectList(_context.Destino, "Id", "Destino", compras.DestinoId);
            return View(compras);
        }

        // GET: Vendas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compras = await _context.Compra.FindAsync(id);
            if (compras == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Cliente, "Id", "Nome", compras.ClienteId);
            ViewData["DestinoId"] = new SelectList(_context.Destino, "Id", "Destino", compras.DestinoId);
            return View(compras);
        }

        // POST: Vendas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ClienteId,DestinoId")] Compras compras)
        {
            if (id != compras.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compras);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComprasExists(compras.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Cliente, "Id", "Email", compras.ClienteId);
            ViewData["DestinoId"] = new SelectList(_context.Destino, "Id", "Id", compras.DestinoId);
            return View(compras);
        }

        // GET: Vendas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compras = await _context.Compra
                .Include(c => c.cliente)
                .Include(c => c.destino)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (compras == null)
            {
                return NotFound();
            }

            return View(compras);
        }

        // POST: Vendas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var compras = await _context.Compra.FindAsync(id);
            _context.Compra.Remove(compras);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComprasExists(int id)
        {
            return _context.Compra.Any(e => e.Id == id);
        }
    }
}

SiteAgencia/Controllers/ViagensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SiteAgencia.Models;

namespace SiteAgencia.Controllers
{
    public class ViagensController : Controller
    {
        private readonly Conectar _context;

        public ViagensController(Conectar context)
        {
            _context = context;
        }

        // GET: Viagens
        public async Task<IActionResult> Index()
        {
            return View(await _context.Destino.ToListAsync());
        }

        // GET: Viagens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destinos = await _context.Destino
                .FirstOrDefaultAsync(m => m.Id == id);
            if (destinos == null)
            {
                return NotFound();
            }

            return View(destinos);
        }

        // GET: Viagens/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Viagens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Destino,Descricao,Valor")] Destinos destinos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(destinos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(destinos);
        }

        // GET: Viagens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destinos = await _context.Destino.FindAsync(id);
            if (destinos == null)
            {
                return NotFound();
            }
            return View(destinos);
        }

        // POST: Viagens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Destino,Descricao,Valor")] Destinos destinos)
        {
            if (id != destinos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(destinos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DestinosExists(destinos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(destinos);
        }

        // GET: Viagens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destinos = await _context.Destino
                .FirstOrDefaultAsync(m => m.Id == id);
            if (destinos == null)
            {
                return NotFound();
            }

            return View(destinos);
        }

        // POST: Viagens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var destinos = await _context.Destino.FindAsync(id);
            _context.Destino.Remove(destinos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DestinosExists(int id)
        {
            return _context.Destino.Any(e => e.Id == id);
        }
    }
}

SiteAgencia/Views/Shared/_Layout.cshtml
@{ViewData["Title"] = "naBahia Turismo";}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut/icon" type="image/png" href="~/favicon.pgn"> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="~/css/style.css">
    <title>@ViewData["Title"]</title>
</head>

<body>
    <header class="position-relative">
        <!--NAVBAR TOPO-->
        <nav class="container-fluid navbar navbar-expand-lg navbar-light bg-info cor-navbar d-flex ">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><img class="logo" src="~/img/logo.png" alt=""></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                        aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Destinos" asp-action="Index">Destinos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Promocoes">Promoções</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Contatos" asp-action="Create">Contatos</a>
                        </li>
                    </ul>
                            <a onclick="alert('Pagina privada apenas a pessoas atorizadas, em breve estará disponivel sistema de login, para facilitar a visualização ela estará disponivel')" class="btn btn-outline-light " asp-controller="Vendas" asp-action="Index">Painel</a>
                </div>
            </div>
        </nav>

        <!--NAVBAR TOPO FIM-->
    </header>
        @RenderBody()
 <footer style="background-color: #611a00;);" class="footer container-fluid position-relative row text-white mt-5">
    <section class="col-12 col-lg-4">
        <hr>
        <h3>Mapa do site</h3>
        <p>Home <hr> Destinos <hr> Promoções <hr> Contatos <hr> Painel</p>
    </section>
    <Section class="col-12 col-lg-4 text-center">
        <hr>
        <h3>Valores da Empresa</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste quo, beatae aliquid, accusantium corrupti voluptatem quae mollitia adipisci, facilis voluptatum architecto ipsum magni iure velit dolore nulla soluta eius earum.</p>
    </Section>
    <section class="col-12 col-lg-4 text-end">
        <hr>
        <h3>Endereço</h3>
        <p>Avenida paralela, Salvador-ba 540</p>
        <h3>Contato</h3>
        <p>Tel:71 98501-1600</p>
    </section>
</footer>   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>

</html>

SiteAgencia/Views/Shared/_LayoutCliente.cshtml
@{ViewData["Title"] = "naBahia Turismo";}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/gif" href="~/animated_favicon1.gif"> 
    <link rel="shortcut/icon" href="~/favicon.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <title>
        "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/style.css">
        <title>@ViewData["Title"]</title>
</head>

<body class="container-fluid p-0 row d-flex justify-content-center m-0">
    <header class=" col-12 vh-lg-100 col-lg-3">
        <img src="~/img/logo.png" alt="Logo do Turista" class="col-12">
        <nav class="navbar navbar-dark navbar-expand-lg container-fluid">
            <button class="navbar-toggler bg-danger container-fluid" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                <div class="container-fluid">
                    <span class="navbar-toggler-icon"></span>
            </button>
            </div>
        </nav>

        <div class="navbar" id="navbarToggleExternalContent">
            <div class="bg-white col-12">

                <a class="btn btn-primary text-white col-12 m-1" asp-controller="Vendas" asp-action="Index">Vender</a>
                <a class="btn btn-info text-dark col-12 m-1" asp-controller="Clientes" asp-action="Index">Clientes</a>
                <a class="btn btn-info text-dark text-decoration-none col-12 m-1" asp-controller="Viagens" asp-action="Index">Destinos</a>
                <a class="btn btn-info text-dark text-decoration-none col-12 m-1" asp-controller="Mensagens" asp-action="Index">Mensagens</a>
                <br />
                <!-- Button trigger modal -->
                <a type="button" class="btn btn-info w-100" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Documentação</a>
                <a class="btn btn-info text-dark col-12 m-1" asp-controller="Home" asp-action="Index">Voltar ao Site</a>
            </div>
        </div>
    </header>
    <main class="col-12 col-lg-9  d-flex flex-column vh-100 mt-5 border border-1">
        @RenderBody()
    </main>
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Instruções de uso do sistema</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h3>Vender</h3>
        <p>Na aba Vender você poderá realizar uma venda a um cliente já cadastrado no sistema.</p>
        <h3>Clientes</h3>
        <p>Na aba Clientes podemos cadastrar o cliente no sistema para realizar vendas</p>
        <h3>Destinos</h3>
        <b> Está aba reflete no site principal</b>
        <p>Na aba Destinos é possivel definir novos destinos, editar, ver detalhes e apagar. Os Destinos cadastrados aparecerar disponivel na interface publica para o cliente</p>
        <h3>Mensagens</h3>
        <p>Aqui recebemos as mensagens vindas do pagina contatos enviadas pelos clientes</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
</body>

</html>